# Dependencies
highlighter:      rouge

gems:
  - jekyll-paginate
  - jekyll-feed

# Permalinks
permalink:              /blog/:categories/:title/
# permalink:            blog/:categories/:year/:month/:day/:title/

# Setup
title:            'Safeer Khan'
name:             'Safeer Khan'
#tagline:          ''
description:      'Software Engineer'
#url:              safeer2978.github.io/
baseurl:           safeer2978.github.io/portfolio
# blogurl:          /blog/

# Assets
images:         '/img'
pdfs:           '/pdf'

author:
  name:           'Safeer Khan'
  url:             safeer2978.github.io
  email:          'safeerkhan2978@gmail.com'
  github:         'https://github.com/safeer2978'
  #facebook:       'http://www.facebook.com/anjana.vakil'
  #twitter:        'https://twitter.com/AnjanaVakil'
  #googleplus:     ''
  linkedin:       'https://www.linkedin.com/in/safeer2978 '

paginate:         3
paginate_path:    "/projects/page:num/"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/safeer2978

# Collections
collections:
  - projects
  - talks

# defaults:
#   -
#     scope:
#       path: ""
#       type: "projects" # a collection in your site, in plural form
#     values:
#       layout: "default"
